/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cnftSol from "./CNFT.sol";
export type { cnftSol };
export type { ArtistPayment } from "./ArtistPayment";
export type { EventTicketContract } from "./EventTicketContract";
