/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cnftSol from "./CNFT.sol";
export type { cnftSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { ArtistPayment } from "./ArtistPayment";
export type { EventTicketBase } from "./EventTicketBase";
export type { EventTicketManager } from "./EventTicketManager";
